config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about" => "pages#about"
  get "contact" => "pages#contact"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


	<%= link_to "About", about_path %>
	<%= link_to "Contact", contact_path %>
	<%= link_to "Home", root_path %>

<%= yield %>

</body>
</html>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>We are working on out OneMonth Rails pinteresting app!</p>

app/views/pages/contact.html.erb
<h1> Contact </h1>
<p> For any questions please feel free to contact us </p>

app/views/pages/home.html.erb
<h1>Welcome to my App</h1>
<p>Sign up <%= link_to "here", "http://www.google.com" %></p>